enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "LisoUseInAIKyrios/revanced-cli"
# cli-version = "6.0.0-dev.2"
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
dpi = "120-640dpi"
arch = "arm64-v8a"
app-name = "X"
patches-source = "crimera/piko"
# rv-brand = "dev"
patches-version = "v2.0.0-dev.13"
build-mode = "both"
riplib = true

[Twitter-it]
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
dpi = "120-640dpi"
arch = "arm64-v8a"
app-name = "X-it"
patches-source = "speedlorenzo12/piko-it"
patches-version = "latest"
build-mode = "both"
riplib = true

[Re-Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
dpi = "120-640dpi"
arch = "arm64-v8a"
app-name = "Re-X"
patches-source = "LisoUseInAIKyrios/revanced-patches"
patches-version = "latest"
build-mode = "both"
riplib = true
