enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
version = "latest"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Hide view count' 'Change link sharing domain'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"
version = "latest"

[X-piko]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
patches-version = "Pre-release"
arch = "arm64-v8a"
version = "beta"
