enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Messenger]
apkmirror-dlurl = "https://apkpure.com/facebook-messenger/com.facebook.orca"
arch = "arm64-v8a"
version = "latest"

[Twitter]
apkmirror-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android/"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Hide view count' 'Change link sharing domain'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[Facebook]
apkmirror-dlurl = "https://apkpure.com/facebook-2025/com.facebook.katana"
arch = "arm64-v8a"
version = "latest"

[X-piko]
apkmirror-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
patches-version = "v2.0.0-dev.12"
arch = "arm64-v8a"
version = "latest"
