enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "LisoUseInAIKyrios/revanced-cli"
# cli-source = "MarcaDian/revanced-cli"
# cli-version = "6.0.0-dev.2"
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[RVX-R]
build-mode = "apk"
patches-source = "LisoUseInAIKyrios/revanced-patches"
excluded-patches = "'Theme' 'GmsCore support'"
patcher-args = "-e 'Custom branding' -OcustomName=RVX-R -e 'Change package name' -Ocustom=r.youtube.rvx"
version = "latest"
arch = "arm64-v8a"
riplip = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
