enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
# cli-source = "inotia00/revanced-cli"
# cli-source = "MarcaDian/revanced-cli"
# cli-version = "6.0.0-dev.2"
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
app-name = "X"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
dpi = "120-640dpi"
arch = "arm64-v8a"
version = "formerly-twitter-11-22-0-release-0"
patches-source = "crimera/piko"
patches-version = "v1.59.0"
build-mode = "apk"
riplib = true
# enabled = false
# excluded-patches = "'Change version code'"
# included-patches = "'Export all activities'"
# cli-version = "v4.6.0"
# rv-brand = "Piko"
# integrations-source = "crimera/revanced-integrations"
