# enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
# cli-source = "inotia00/revanced-cli"
patches-source = "crimera/piko"
patches-version = "v3.0.0-dev.1"
# integrations-source = "crimera/revanced-integrations"
# cli-source = "crimera/piko"
# cli-version = "v4.6.2"
# rv-brand = "Piko"
# cli-source = "MarcaDian/revanced-cli"
# cli-version = "6.0.0-dev.2"
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[X]
# app-name = "X"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
dpi = "120-640dpi"
arch = "arm64-v8a"
version = "formerly-twitter-11-20-0-release-0"
# patches-version = "v2.0.0-dev.17"
build-mode = "apk"
riplib = true
# excluded-patches = "'Bring back twitter' 'Dynamic color' 'Disunify xchat system'"
# patcher-args = "-e 'Change version code' -OVersioncode=999999999"
# enabled = false
# excluded-patches = "'Change version code'"
# included-patches = "'Export all activities'"
# cli-source = "crimera/revanced-integrations"
# cli-version = "v4.6.0"
# rv-brand = "Piko"
# integrations-source = "crimera/revanced-integrations"
